### ISSUE TITLE
Optional fields in proto massages

### ISSUE THREAD

**Issue by somespecialone** [Gobot1234/steam-ext-csgo#6]
Hi! I see that in [cstrike15_gcmessages.proto](https://github.com/ValvePython/csgo/blob/master/protobufs/cstrike15_gcmessages.proto#L801-L829) or [cstrike15_gcmessages.proto](https://github.com/DoctorMcKay/node-globaloffensive/blob/master/protobufs/cstrike15_gcmessages.proto#L817-L845) in [node-csgo](https://github.com/DoctorMcKay/node-globaloffensive) fields are optional, but [there in generated protobufs](https://github.com/Gobot1234/steam-ext-csgo/blob/main/steam/ext/csgo/protobufs/cstrike.py#L785-L814) not.

It not so scary, but a few problems arrives:

1. Noisy info in inspected items(`empty` fields with zero value);
2. It is not possible to distinguish item with `stattrek` and another quality from non-stattrek item.

You can see second problem in [csgofloat-inspect](https://github.com/csgofloat/inspect/blob/master/lib/game_data.js#L324-L327):
```js
// Patch for items that are stattrak and unusual (ex. Stattrak Karambit)
if (iteminfo.killeatervalue !== null && iteminfo.quality !== 9) {
    name += `${this.csgo_english['strange']} `;
}
```
I think i can monkey patch this in my code, but decided to tell you about problems, thanks!

**Comment by somespecialone** [comment]
Forgot to write: now items with stattrek have killeatervalue == 0 and items without stattrek have killeatervalue with zero value and this messes all up.

**Comment by Gobot1234** [comment]
With betterproto b4 I can probably fix this this, but it would break a lot of my code, so I'm inclined to only  to only do this on specific fields

**Comment by somespecialone** [comment]
Understand, so can i ask you to fix just killeatervalue to be optional?

**Comment by Gobot1234** [comment]
Would you mind opening a PR for it, I'm a little swamped? All you'd need to do is pass optional=True to the field function

**Comment by somespecialone** [comment]
#7
